spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blogdb
    username: sa
    password:

  jpa:
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
blog:
  search:
    kakao:
      api-uri: ${KAKAO_API_URI}
      api-key: ${KAKAO_API_KEY}
    naver:
      api-uri: ${NAVER_API_URI}
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}

logging:
  level:
    com.smc2315.blogsearch: debug

