spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blogdb
    username: sa
    password:

  jpa:
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console